Hide progress bar 279
Ryczko/FormsLab pull request #285
Opened 2024-01-25 20:55 UTC by DevDaniloFerrari

#279 

![image](https://github.com/Ryczko/FormsLab/assets/40414119/e79a0dee-7a82-4c6f-889b-8ec304ccee1a)
![image](https://github.com/Ryczko/FormsLab/assets/40414119/bba59b00-023a-424f-88af-bed1c274f1ae)

2024-01-27 11:33 UTC, Ryczko requested changes
Hi, It is not correct solution. That setting should be store in database in Survey model, and display view should use also this data from there

2024-01-28 01:55 UTC, DevDaniloFerrari commented
Great! I'll make these changes.

2024-01-28 09:56 UTC, Ryczko requested changes

2024-01-28 09:56 UTC, Ryczko commented on src/features/surveys/features/SurveyDisplay/components/OneQuestionView/OneQuestionView.tsx
> +  const { surveyOptions } = useSurveyCreatorContext();
Still we should not use `useSurveyCreatorContext` here. We should take `formData.hideProgressBar` from `useSurveyDisplayContext`

2024-01-28 09:56 UTC, Ryczko commented on src/features/surveys/features/SurveyDisplay/components/OneQuestionView/OneQuestionView.tsx
> +  const { surveyOptions } = useSurveyCreatorContext();
Otherwise that option will not work while sharing survey

2024-01-28 10:30 UTC, merged